import { dayLabel, type CatalogProfessor, type CatalogRoom, type ScheduleEntry, type Subject } from "@/lib/schedule-data";

type CatalogKind = "subjects" | "professors" | "rooms";

export function CatalogBoard({ schedule, subjects = [], professors = [], rooms = [], kind, onSelectSubject }: { schedule: ScheduleEntry[]; subjects?: Subject[]; professors?: CatalogProfessor[]; rooms?: CatalogRoom[]; kind: CatalogKind; onSelectSubject: (entry: ScheduleEntry) => void }) {
  const title = kind === "subjects" ? "Materias" : kind === "professors" ? "Profesores" : "Aulas";
  const description = kind === "subjects" ? "Catálogo de materias y sus categorías." : kind === "professors" ? "Docentes y clases asociadas en tu semana." : "Aulas asignadas a cada clase.";
  const groups = kind === "subjects" ? subjects.map((subject) => ({ label: subject.code, title: subject.name, items: schedule.filter((entry) => entry.subjectId === subject.id), key: subject.id })) : kind === "professors" ? professors.map((professor) => ({ label: professor.display_name, title: professor.display_name, items: schedule.filter((entry) => entry.professor === professor.display_name), key: professor.id })) : rooms.map((room) => ({ label: room.name, title: room.name, items: schedule.filter((entry) => entry.room === room.name), key: room.id }));

  return <section aria-label={title} className="mx-auto max-w-5xl"><div className="mb-7"><h1 className="text-[22px] font-bold tracking-[-0.03em] text-[var(--ink)]">{title}</h1><p className="mt-1 text-sm leading-6 text-[var(--muted)]">{description}</p></div><div className="grid gap-4 sm:grid-cols-2">{groups.map((group) => <article key={group.key} className="rounded-2xl border border-[var(--line)] bg-[var(--surface)] p-5"><p className="text-xs font-bold tracking-[0.12em] text-[var(--accent)] uppercase">{group.label}</p>{kind === "subjects" && group.items[0] ? <button type="button" onClick={() => onSelectSubject(group.items[0])} className="mt-3 w-full rounded-xl bg-[var(--background)] p-4 text-left transition hover:border-[var(--accent)] hover:shadow-md focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[var(--accent)]"><span className="text-[10px] font-bold tracking-[0.12em] text-[var(--muted)] uppercase">{group.items[0].code} · {Array.from(new Set(group.items.map((item) => item.section))).join(" · ")}</span><strong className="mt-2 block text-sm text-[var(--ink)]">{group.title}</strong><span className="mt-2 block text-xs text-[var(--muted)]">{group.items.length} sesiones semanales</span></button> : <ul className="mt-3 space-y-2">{group.items.map((entry) => <li key={entry.id}><button type="button" onClick={() => onSelectSubject(entry)} className="w-full rounded-lg px-2 py-2 text-left transition hover:bg-[var(--soft)] focus-visible:outline-2 focus-visible:outline-[var(--accent)]"><span className="block text-sm font-semibold text-[var(--ink)]">{entry.subject}</span><span className="block text-xs text-[var(--muted)]">{dayLabel(entry.day)} · {entry.start}–{entry.end} · {entry.section}</span></button></li>)}</ul>}</article>)}</div></section>;
}
